web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
jwt:
  secret: "#%34Rrdasf"
spring:
  sql:
    init:
      platform: postgres
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: [DATABASE_SCHEMA]
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: [DATABASE_USER]
    password: [DATABASE_PASSWORD]
    url: jdbc:postgresql://[DATABASE_URL]:[DATABASE_PORT]/[DATABASE_NAME]
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
